
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: jwt-token
          uri: https://github.com/Kalek5412/microservice-feign
          search-paths: config-data
  application:
    name: config-server

